// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginPage() {
    driver.get("https://practicesoftwaretesting.com/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.cssSelector("*[data-test=\"nav-sign-in\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"register-link\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"first-name\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"first-name\"]")).sendKeys("Tahlil");
    driver.findElement(By.cssSelector("*[data-test=\"last-name\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"last-name\"]")).sendKeys("Mahfuz");
    driver.findElement(By.cssSelector("*[data-test=\"dob\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"dob\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"dob\"]")).sendKeys("2024-07-31");
    driver.findElement(By.cssSelector("*[data-test=\"address\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"address\"]")).sendKeys("Dhaka");
    driver.findElement(By.cssSelector(".col-md-4")).click();
    driver.findElement(By.cssSelector("*[data-test=\"postcode\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"postcode\"]")).sendKeys("1001");
    driver.findElement(By.cssSelector("*[data-test=\"city\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"city\"]")).sendKeys("Dhaka");
    driver.findElement(By.cssSelector("*[data-test=\"state\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"state\"]")).sendKeys("Dhaka");
    driver.findElement(By.cssSelector("*[data-test=\"country\"]")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("*[data-test=\"country\"]"));
      dropdown.findElement(By.xpath("//option[. = 'Bangladesh']")).click();
    }
    driver.findElement(By.cssSelector(".form-group:nth-child(9)")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(9)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".form-group:nth-child(9)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("*[data-test=\"phone\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"phone\"]")).sendKeys("123421341241");
    driver.findElement(By.cssSelector("*[data-test=\"email\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"email\"]")).sendKeys("practice@gmail.com");
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("12345314142");
    driver.findElement(By.cssSelector("*[data-test=\"register-submit\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"dob\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"dob\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"dob\"]")).sendKeys("2003-07-31");
    driver.findElement(By.cssSelector("*[data-test=\"register-submit\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("12345314142ASDFWDW");
    driver.findElement(By.cssSelector("*[data-test=\"register-submit\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("12345314142ASDFWDW!@@");
    driver.findElement(By.cssSelector(".ng-dirty > .row")).click();
    driver.findElement(By.cssSelector("*[data-test=\"register-submit\"]")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(11)")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
    driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("12345314142ASDFWDW!@@Fa");
    driver.findElement(By.cssSelector("*[data-test=\"register-submit\"]")).click();
  }
}
